use chrono::{NaiveDate, DateTime, Utc};
use rust_decimal::Decimal;
use finq_core::OptionType;
use serde::{Serialize, Deserialize};

use crate::value_objects::*;

/// Earnings event for a symbol
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EarningsEvent {
    pub symbol: String,
    pub earnings_date: NaiveDate,
    pub earnings_time: EarningsTime,
    pub company_name: Option<String>,
    pub eps_forecast: Option<Decimal>,
    pub market_cap: Option<u64>,
}

impl EarningsEvent {
    pub fn new(symbol: String, earnings_date: NaiveDate, earnings_time: EarningsTime) -> Self {
        Self {
            symbol,
            earnings_date,
            earnings_time,
            company_name: None,
            eps_forecast: None,
            market_cap: None,
        }
    }

    pub fn with_market_cap(mut self, market_cap: u64) -> Self {
        self.market_cap = Some(market_cap);
        self
    }

    pub fn with_company_name(mut self, name: String) -> Self {
        self.company_name = Some(name);
        self
    }
}

/// Single option leg
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptionLeg {
    pub symbol: String,
    pub strike: Strike,
    pub expiration: NaiveDate,
    pub option_type: OptionType,
}

impl OptionLeg {
    pub fn new(
        symbol: String,
        strike: Strike,
        expiration: NaiveDate,
        option_type: OptionType,
    ) -> Self {
        Self { symbol, strike, expiration, option_type }
    }

    /// Generate OCC ticker (e.g., "O:AAPL250117C00180000")
    pub fn occ_ticker(&self) -> String {
        let opt_char = match self.option_type {
            OptionType::Call => 'C',
            OptionType::Put => 'P',
        };
        // Convert strike to cents (multiply by 1000 for OCC format)
        let strike_millis = self.strike.value() * Decimal::from(1000);
        // Round to nearest integer and convert
        let strike_int = strike_millis.round().to_string()
            .split('.')
            .next()
            .and_then(|s| s.parse::<u64>().ok())
            .unwrap_or(0);
        format!(
            "O:{}{}{}{}",
            self.symbol,
            self.expiration.format("%y%m%d"),
            opt_char,
            format!("{:08}", strike_int)
        )
    }

    /// Days to expiry from given date
    pub fn dte(&self, from: NaiveDate) -> i32 {
        (self.expiration - from).num_days() as i32
    }
}

/// Calendar spread = short near-term + long far-term
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarSpread {
    pub short_leg: OptionLeg,
    pub long_leg: OptionLeg,
}

impl CalendarSpread {
    pub fn new(short: OptionLeg, long: OptionLeg) -> Result<Self, ValidationError> {
        if short.symbol != long.symbol {
            return Err(ValidationError::SymbolMismatch(
                short.symbol.clone(),
                long.symbol.clone(),
            ));
        }
        if short.expiration >= long.expiration {
            return Err(ValidationError::ExpirationMismatch {
                short: short.expiration,
                long: long.expiration,
            });
        }
        Ok(Self { short_leg: short, long_leg: long })
    }

    pub fn symbol(&self) -> &str { &self.short_leg.symbol }
    pub fn strike(&self) -> Strike { self.short_leg.strike }
    pub fn option_type(&self) -> OptionType { self.short_leg.option_type }
    pub fn short_expiry(&self) -> NaiveDate { self.short_leg.expiration }
    pub fn long_expiry(&self) -> NaiveDate { self.long_leg.expiration }
}

/// Trade opportunity generated by strategy
#[derive(Debug, Clone)]
pub struct TradeOpportunity {
    pub spread: CalendarSpread,
    pub earnings_event: EarningsEvent,
    pub entry_time: DateTime<Utc>,
    pub exit_time: DateTime<Utc>,
    pub spot_price_at_selection: SpotPrice,
}

/// Completed trade result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalendarSpreadResult {
    // Identification
    pub symbol: String,
    pub earnings_date: NaiveDate,
    pub earnings_time: EarningsTime,
    pub strike: Strike,
    pub option_type: OptionType,
    pub short_expiry: NaiveDate,
    pub long_expiry: NaiveDate,

    // Entry
    pub entry_time: DateTime<Utc>,
    pub short_entry_price: Decimal,
    pub long_entry_price: Decimal,
    pub entry_cost: Decimal,

    // Exit
    pub exit_time: DateTime<Utc>,
    pub short_exit_price: Decimal,
    pub long_exit_price: Decimal,
    pub exit_value: Decimal,

    // P&L
    pub pnl: Decimal,
    pub pnl_per_contract: Decimal,
    pub pnl_pct: Decimal,

    // Greeks at entry
    pub short_delta: Option<f64>,
    pub short_gamma: Option<f64>,
    pub short_theta: Option<f64>,
    pub short_vega: Option<f64>,
    pub long_delta: Option<f64>,
    pub long_gamma: Option<f64>,
    pub long_theta: Option<f64>,
    pub long_vega: Option<f64>,

    // IV at entry/exit
    pub iv_short_entry: Option<f64>,
    pub iv_long_entry: Option<f64>,
    pub iv_short_exit: Option<f64>,
    pub iv_long_exit: Option<f64>,

    // P&L Attribution
    pub delta_pnl: Option<Decimal>,
    pub gamma_pnl: Option<Decimal>,
    pub theta_pnl: Option<Decimal>,
    pub vega_pnl: Option<Decimal>,
    pub unexplained_pnl: Option<Decimal>,

    // Spot prices
    pub spot_at_entry: f64,
    pub spot_at_exit: f64,

    // Status
    pub success: bool,
    pub failure_reason: Option<FailureReason>,
}

impl CalendarSpreadResult {
    pub fn iv_ratio(&self) -> Option<f64> {
        match (self.iv_short_entry, self.iv_long_entry) {
            (Some(short), Some(long)) if long > 0.0 => Some(short / long),
            _ => None,
        }
    }

    pub fn is_winner(&self) -> bool {
        self.success && self.pnl > Decimal::ZERO
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_earnings_event_new() {
        let event = EarningsEvent::new(
            "AAPL".to_string(),
            NaiveDate::from_ymd_opt(2025, 6, 20).unwrap(),
            EarningsTime::AfterMarketClose,
        );

        assert_eq!(event.symbol, "AAPL");
        assert_eq!(event.earnings_time, EarningsTime::AfterMarketClose);
        assert!(event.market_cap.is_none());
    }

    #[test]
    fn test_earnings_event_builder() {
        let event = EarningsEvent::new(
            "AAPL".to_string(),
            NaiveDate::from_ymd_opt(2025, 6, 20).unwrap(),
            EarningsTime::AfterMarketClose,
        )
        .with_market_cap(3_000_000_000_000)
        .with_company_name("Apple Inc.".to_string());

        assert_eq!(event.market_cap, Some(3_000_000_000_000));
        assert_eq!(event.company_name, Some("Apple Inc.".to_string()));
    }

    #[test]
    fn test_option_leg_occ_ticker() {
        let leg = OptionLeg::new(
            "AAPL".to_string(),
            Strike::new(Decimal::new(180, 0)).unwrap(),
            NaiveDate::from_ymd_opt(2025, 1, 17).unwrap(),
            OptionType::Call,
        );

        let ticker = leg.occ_ticker();
        assert_eq!(ticker, "O:AAPL250117C00180000");
    }

    #[test]
    fn test_option_leg_occ_ticker_put() {
        let leg = OptionLeg::new(
            "AAPL".to_string(),
            Strike::new(Decimal::new(1755, 1)).unwrap(), // 175.5
            NaiveDate::from_ymd_opt(2025, 1, 17).unwrap(),
            OptionType::Put,
        );

        let ticker = leg.occ_ticker();
        assert_eq!(ticker, "O:AAPL250117P00175500");
    }

    #[test]
    fn test_option_leg_dte() {
        let leg = OptionLeg::new(
            "AAPL".to_string(),
            Strike::new(Decimal::new(180, 0)).unwrap(),
            NaiveDate::from_ymd_opt(2025, 1, 17).unwrap(),
            OptionType::Call,
        );

        let from_date = NaiveDate::from_ymd_opt(2025, 1, 10).unwrap();
        assert_eq!(leg.dte(from_date), 7);
    }

    #[test]
    fn test_calendar_spread_valid() {
        let short = OptionLeg::new(
            "AAPL".to_string(),
            Strike::new(Decimal::new(180, 0)).unwrap(),
            NaiveDate::from_ymd_opt(2025, 1, 17).unwrap(),
            OptionType::Call,
        );

        let long = OptionLeg::new(
            "AAPL".to_string(),
            Strike::new(Decimal::new(180, 0)).unwrap(),
            NaiveDate::from_ymd_opt(2025, 1, 31).unwrap(),
            OptionType::Call,
        );

        let spread = CalendarSpread::new(short, long);
        assert!(spread.is_ok());

        let spread = spread.unwrap();
        assert_eq!(spread.symbol(), "AAPL");
        assert_eq!(spread.option_type(), OptionType::Call);
    }

    #[test]
    fn test_calendar_spread_symbol_mismatch() {
        let short = OptionLeg::new(
            "AAPL".to_string(),
            Strike::new(Decimal::new(180, 0)).unwrap(),
            NaiveDate::from_ymd_opt(2025, 1, 17).unwrap(),
            OptionType::Call,
        );

        let long = OptionLeg::new(
            "GOOGL".to_string(),
            Strike::new(Decimal::new(180, 0)).unwrap(),
            NaiveDate::from_ymd_opt(2025, 1, 31).unwrap(),
            OptionType::Call,
        );

        let spread = CalendarSpread::new(short, long);
        assert!(spread.is_err());
        assert!(matches!(spread.unwrap_err(), ValidationError::SymbolMismatch(_, _)));
    }

    #[test]
    fn test_calendar_spread_expiration_mismatch() {
        let short = OptionLeg::new(
            "AAPL".to_string(),
            Strike::new(Decimal::new(180, 0)).unwrap(),
            NaiveDate::from_ymd_opt(2025, 1, 31).unwrap(),
            OptionType::Call,
        );

        let long = OptionLeg::new(
            "AAPL".to_string(),
            Strike::new(Decimal::new(180, 0)).unwrap(),
            NaiveDate::from_ymd_opt(2025, 1, 17).unwrap(),
            OptionType::Call,
        );

        let spread = CalendarSpread::new(short, long);
        assert!(spread.is_err());
        assert!(matches!(spread.unwrap_err(), ValidationError::ExpirationMismatch { .. }));
    }

    #[test]
    fn test_calendar_spread_result_iv_ratio() {
        let result = CalendarSpreadResult {
            symbol: "AAPL".to_string(),
            earnings_date: NaiveDate::from_ymd_opt(2025, 6, 20).unwrap(),
            earnings_time: EarningsTime::AfterMarketClose,
            strike: Strike::new(Decimal::new(180, 0)).unwrap(),
            option_type: OptionType::Call,
            short_expiry: NaiveDate::from_ymd_opt(2025, 1, 17).unwrap(),
            long_expiry: NaiveDate::from_ymd_opt(2025, 1, 31).unwrap(),
            entry_time: Utc::now(),
            short_entry_price: Decimal::new(5, 0),
            long_entry_price: Decimal::new(6, 0),
            entry_cost: Decimal::new(1, 0),
            exit_time: Utc::now(),
            short_exit_price: Decimal::new(2, 0),
            long_exit_price: Decimal::new(4, 0),
            exit_value: Decimal::new(2, 0),
            pnl: Decimal::new(1, 0),
            pnl_per_contract: Decimal::new(1, 0),
            pnl_pct: Decimal::new(100, 0),
            short_delta: None,
            short_gamma: None,
            short_theta: None,
            short_vega: None,
            long_delta: None,
            long_gamma: None,
            long_theta: None,
            long_vega: None,
            iv_short_entry: Some(0.30),
            iv_long_entry: Some(0.25),
            iv_short_exit: None,
            iv_long_exit: None,
            delta_pnl: None,
            gamma_pnl: None,
            theta_pnl: None,
            vega_pnl: None,
            unexplained_pnl: None,
            spot_at_entry: 180.0,
            spot_at_exit: 182.0,
            success: true,
            failure_reason: None,
        };

        assert_eq!(result.iv_ratio(), Some(1.2));
    }

    #[test]
    fn test_calendar_spread_result_is_winner() {
        let mut result = CalendarSpreadResult {
            symbol: "AAPL".to_string(),
            earnings_date: NaiveDate::from_ymd_opt(2025, 6, 20).unwrap(),
            earnings_time: EarningsTime::AfterMarketClose,
            strike: Strike::new(Decimal::new(180, 0)).unwrap(),
            option_type: OptionType::Call,
            short_expiry: NaiveDate::from_ymd_opt(2025, 1, 17).unwrap(),
            long_expiry: NaiveDate::from_ymd_opt(2025, 1, 31).unwrap(),
            entry_time: Utc::now(),
            short_entry_price: Decimal::new(5, 0),
            long_entry_price: Decimal::new(6, 0),
            entry_cost: Decimal::new(1, 0),
            exit_time: Utc::now(),
            short_exit_price: Decimal::new(2, 0),
            long_exit_price: Decimal::new(4, 0),
            exit_value: Decimal::new(2, 0),
            pnl: Decimal::new(1, 0),
            pnl_per_contract: Decimal::new(1, 0),
            pnl_pct: Decimal::new(100, 0),
            short_delta: None,
            short_gamma: None,
            short_theta: None,
            short_vega: None,
            long_delta: None,
            long_gamma: None,
            long_theta: None,
            long_vega: None,
            iv_short_entry: None,
            iv_long_entry: None,
            iv_short_exit: None,
            iv_long_exit: None,
            delta_pnl: None,
            gamma_pnl: None,
            theta_pnl: None,
            vega_pnl: None,
            unexplained_pnl: None,
            spot_at_entry: 180.0,
            spot_at_exit: 182.0,
            success: true,
            failure_reason: None,
        };

        assert!(result.is_winner());

        result.pnl = Decimal::new(-1, 0);
        assert!(!result.is_winner());

        result.pnl = Decimal::new(1, 0);
        result.success = false;
        assert!(!result.is_winner());
    }
}
